"""init schema

Revision ID: ec19b03c979c
Revises: 401d05551908
Create Date: 2025-11-06 15:16:38.261586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec19b03c979c'
down_revision: Union[str, Sequence[str], None] = '401d05551908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hololive_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('released_en', sa.Integer(), nullable=False),
    sa.Column('released_jp', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hololive_sets_code'), 'hololive_sets', ['code'], unique=True)
    op.create_index(op.f('ix_hololive_sets_id'), 'hololive_sets', ['id'], unique=False)
    op.create_table('one_piece_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('released_en', sa.Integer(), nullable=False),
    sa.Column('released_jp', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_piece_sets_code'), 'one_piece_sets', ['code'], unique=True)
    op.create_index(op.f('ix_one_piece_sets_id'), 'one_piece_sets', ['id'], unique=False)
    op.create_table('hololive_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('power', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.String(length=32), nullable=True),
    sa.Column('text', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['hololive_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hololive_cards_code'), 'hololive_cards', ['code'], unique=False)
    op.create_index(op.f('ix_hololive_cards_id'), 'hololive_cards', ['id'], unique=False)
    op.create_index(op.f('ix_hololive_cards_language'), 'hololive_cards', ['language'], unique=False)
    op.create_index(op.f('ix_hololive_cards_set_id'), 'hololive_cards', ['set_id'], unique=False)
    op.create_table('one_piece_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('wep_type', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('power', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.String(length=32), nullable=True),
    sa.Column('text', sa.String(length=2048), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['one_piece_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_piece_cards_code'), 'one_piece_cards', ['code'], unique=False)
    op.create_index(op.f('ix_one_piece_cards_id'), 'one_piece_cards', ['id'], unique=False)
    op.create_index(op.f('ix_one_piece_cards_language'), 'one_piece_cards', ['language'], unique=False)
    op.create_index(op.f('ix_one_piece_cards_set_id'), 'one_piece_cards', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_piece_cards_set_id'), table_name='one_piece_cards')
    op.drop_index(op.f('ix_one_piece_cards_language'), table_name='one_piece_cards')
    op.drop_index(op.f('ix_one_piece_cards_id'), table_name='one_piece_cards')
    op.drop_index(op.f('ix_one_piece_cards_code'), table_name='one_piece_cards')
    op.drop_table('one_piece_cards')
    op.drop_index(op.f('ix_hololive_cards_set_id'), table_name='hololive_cards')
    op.drop_index(op.f('ix_hololive_cards_language'), table_name='hololive_cards')
    op.drop_index(op.f('ix_hololive_cards_id'), table_name='hololive_cards')
    op.drop_index(op.f('ix_hololive_cards_code'), table_name='hololive_cards')
    op.drop_table('hololive_cards')
    op.drop_index(op.f('ix_one_piece_sets_id'), table_name='one_piece_sets')
    op.drop_index(op.f('ix_one_piece_sets_code'), table_name='one_piece_sets')
    op.drop_table('one_piece_sets')
    op.drop_index(op.f('ix_hololive_sets_id'), table_name='hololive_sets')
    op.drop_index(op.f('ix_hololive_sets_code'), table_name='hololive_sets')
    op.drop_table('hololive_sets')
    # ### end Alembic commands ###
